spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ##    url: jdbc:mysql://host.docker.internal:3306/parang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/homedb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: home
    password: 1245

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  level:
    com.vowing.parang: debug
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

jwt:
  AccessSecret : askdjnasjkdaskdjnasjkdaskdjnasjkdaskdjnasjkdaskdjnasjkdaskdjnasjkdaskdjnasjkdaskdjnasjkdaskdjnasjkd
  AccessExpiration : 86400000 # 24 hours #30000 # 30초
  RefreshExpiration : 86400000 # ??

cloud:
  aws:
    credentials:
      accessKey: ${accessKey}
      secretKey: ${secretKey}
    s3:
      bucket: s3jominuk
    region:
      static: ap-northeast-2
    stack:
      auto: false